inherit_from: .rubocop_todo.yml

Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
NumericLiterals:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/IfUnlessModifier:
  Enabled: false
Style/StringLiterals:
  Enabled: false
