name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: mysql_user
          MYSQL_DATABASE: sample_db
          MYSQL_USER: mysql_user
          MYSQL_PASSWORD: mysql_user
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      api:
        build:
          context: .
        volumes:
          - .:/app
        depends_on:
          - mysql
        env:
          RAILS_ENV: test
          DATABASE_URL: "mysql2://mysql_user:mysql_user@mysql:3306/sample_db"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
          yarn install
      - name: Run tests
        run: bundle exec rails test
